# Generated by Django 4.1.7 on 2023-03-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0004_alter_menuentity_menu_alter_menuentity_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'menu', 'verbose_name_plural': 'menus'},
        ),
        migrations.AlterField(
            model_name='menu',
            name='named_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='unique_name'),
        ),
    ]
