# Generated by Django 4.1.7 on 2023-03-01 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0005_alter_menu_options_alter_menu_named_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuentity',
            options={'verbose_name': 'menu entity', 'verbose_name_plural': 'menu entities'},
        ),
    ]
