# Generated by Django 4.1.7 on 2023-03-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0006_alter_menuentity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.CharField(default=1, max_length=255, verbose_name='url'),
            preserve_default=False,
        ),
    ]
