# Generated by Django 4.1.7 on 2023-03-03 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0008_alter_menu_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuentity',
            name='url',
        ),
    ]
