# Generated by Django 4.1.7 on 2023-03-03 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0009_remove_menuentity_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='existence',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='order',
        ),
        migrations.RemoveField(
            model_name='menuentity',
            name='existence',
        ),
        migrations.RemoveField(
            model_name='menuentity',
            name='order',
        ),
        migrations.RemoveField(
            model_name='menuentity',
            name='parent',
        ),
        migrations.CreateModel(
            name='SubMenuEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('named_url', models.CharField(blank=True, max_length=255, verbose_name='url pattern')),
                ('menu_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree_menu.menuentity')),
            ],
            options={
                'verbose_name': 'sub-entity',
                'verbose_name_plural': 'sub-entities',
            },
        ),
    ]
