# Generated by Django 4.1.7 on 2023-03-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0010_remove_menu_existence_remove_menu_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='existence',
            field=models.BooleanField(default=True, verbose_name='visibility'),
        ),
        migrations.AddField(
            model_name='menu',
            name='order',
            field=models.IntegerField(default=10, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='menuentity',
            name='existence',
            field=models.BooleanField(default=True, verbose_name='visibility'),
        ),
        migrations.AddField(
            model_name='menuentity',
            name='order',
            field=models.IntegerField(default=10, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='submenuentity',
            name='existence',
            field=models.BooleanField(default=True, verbose_name='visibility'),
        ),
        migrations.AddField(
            model_name='submenuentity',
            name='order',
            field=models.IntegerField(default=10, verbose_name='order'),
        ),
    ]
