# Generated by Django 4.1.7 on 2023-03-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0011_menu_existence_menu_order_menuentity_existence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='named_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='named_url'),
        ),
        migrations.AlterField(
            model_name='menuentity',
            name='named_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='named_url'),
        ),
        migrations.AlterField(
            model_name='submenuentity',
            name='named_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='named_url'),
        ),
    ]
